# Azure Pipelines configuration file for Continuous Integration

jobs:
- job: 'Default'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 10
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'
        ARCH: 'x86'
        PIP_FLAGS: ''
      Python36-x64:
        PYTHON_VERSION: '3.6'
        ARCH: 'x64'
        PIP_FLAGS: ''
      Python37:
        PYTHON_VERSION: '3.7'
        ARCH: 'x86'
        PIP_FLAGS: ''
      Python37-x64:
        PYTHON_VERSION: '3.7'
        ARCH: 'x64'
        PIP_FLAGS: ''
  continueOnError: false
  timeoutInMinutes: 60

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: '$(ARCH)'
    IARRAY_EXTERNAL: 'iarray/external'

- powershell: |
    Write-Host "##vso[task.setvariable variable=PATH;]${env:PYTHON};${env:PYTHON}\Scripts;${env:PATH}";
  displayName: 'Add Python paths to PATH'

- script: |
    @echo on

    :: Update pip
    python -m pip install --retries 3 -U pip setuptools setuptools-scm

    :: Check that we have the expected version and architecture for Python
    python --version
    pip --version
    python -c "import struct; print('Void pointer width is', struct.calcsize('P') * 8)"
    pip list

    :: Install the build and runtime dependencies of the project
    pip install %PIP_FLAGS% --retries 3 -r requirements/default.txt
    pip install %PIP_FLAGS% --retries 3 -r requirements/build.txt
    pip list
  displayName: 'Pre-installation'

- script: |
    @echo on

    :: Get iron-array library from somewhere (TBD)
    :: curl https://raw.somewhere.com/libiarray/iarray.h -o %IARRAY_EXTERNAL%/iarray.h
    :: curl https://raw.somewhere.com/libiarrau/iarray.dll -o %IARRAY_EXTERNAL%/iarray.dll

    :: Compile the package and build the wheel
    python setup.py bdist_wheel

    :: Install the generated wheel package
    dir dist
    pip install %PIP_FLAGS% --no-index --find-links dist/ iarray
  displayName: 'Installation'

- powershell: |
    Write-Host "##vso[task.setvariable variable=PATH;]${env:IARRAY_EXTERNAL};${env:PATH}";
  displayName: 'Add IARRAY_EXTERNAL path to PATH'

- script: |
    @echo on

    :: Install the test dependencies
    pip install %PIP_FLAGS% --retries 3 -r requirements/test.txt
    pip list
  displayName: 'Pre-testing'

- script: |
    @echo on

    :: Default working directory, where the source code is located,
    :: is D:\a\1\s or similar. In order to run the tests on the installed
    :: version of iarray, a different working directory is used.
    echo "Running tests on the following version of iron-array-python:"
        python -c "import iarray; print(iarray.__path__)"

    :: Run unit tests with pytest
    pytest -v --pyargs iarray

    :: [For further consideration]
    :: # -- Build the docs
    :: # -- Publish the .whl artifacts
    :: # -- Upload the content of dist/*.whl to our wheelhouse
  workingDirectory: $(Agent.ToolsDirectory)
  displayName: 'Testing'
