trigger:
- develop

pool:
  vmImage: 'ubuntu-18.04'

container: quay.io/pypa/manylinux2014_x86_64:latest

steps:
- checkout: self
  submodules: recursive
  persistCredentials: true

- bash: |
    mkdir -p $HOME/.inaos/cmake
    mkdir -p $HOME/INAOS
    echo "INAC_REPOSITORY_LOCAL=$HOME/INAOS" > $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_REMOTE=https://inaos.jfrog.io/inaos/libs-release-local/inaos" >> $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_USRPWD=licensed:AKCp5bBraH7CasbsYCURsjzkbjXwVwdYcT7u39EiuL6GjnK1VKfKQWCd1E2E64mHokU5YUHku" >> $HOME/.inaos/cmake/repository.txt
    git submodule update --init --recursive
  displayName: Clone repos

- bash: |
    conda create --yes --quiet --name iArrayEnv
    source activate iArrayEnv
    conda install -y --name iArrayEnv -c intel mkl-include
    conda install -y --name iArrayEnv -c intel mkl-static
    conda install -y --name iArrayEnv -c intel icc_rt
    conda install -y --name iArrayEnv -c numba llvmdev
  displayName: Download dependencies

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
      python -m pip install --retries 3 -U pip setuptools setuptools-scm scikit-build numpy llvmlite cython numexpr
  displayName: 'Install dependencies'

- script: |
      python setup.py build_ext -j 4 --build-type=RelWithDebInfo -- -DDISABLE_LLVM_CONFIG=True -DLLVM_DIR=$CONDA/envs/iArrayEnv/lib/cmake/llvm
  displayName: 'Compile package'

- script: |
      pip install pytest
      LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/envs/iArrayEnv/lib pytest -vv
  displayName: 'Run Tests'
  condition:
    eq( variables['Agent.OS'], 'Linux' )
