trigger:
- develop

variables:
  CONDA_CACHE_FOLDER: $(CONDA)

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python.version: '3.8'
      DISABLE_LLVM_CONFIG: True
    mac:
      imageName: 'macos-10.15'
      python.version: '3.7'
      DISABLE_LLVM_CONFIG: True
#    windows:
#      imageName: 'windows-2022'
#      VSINSTALL: "Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build"
#      MSVC_PLATFORM: amd64
#      python.version: '3.9'

pool:
  vmImage: $(imageName)


steps:
- checkout: self
  submodules: recursive
  persistCredentials: true

- powershell: gci env:* | sort-object name

- bash: |
    mkdir -p $HOME/.inaos/cmake
    mkdir -p $HOME/INAOS
    echo "INAC_REPOSITORY_LOCAL=$HOME/INAOS" > $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_REMOTE=https://inaos.jfrog.io/inaos/libs-release-local/inaos" >> $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_USRPWD=licensed:AKCp5bBraH7CasbsYCURsjzkbjXwVwdYcT7u39EiuL6GjnK1VKfKQWCd1E2E64mHokU5YUHku" >> $HOME/.inaos/cmake/repository.txt
    git submodule update --init --recursive
  displayName: Clone repos

- bash: |
    if [ "$AGENT_OS" == "Darwin" ]
      then
        echo "##vso[task.prependpath]$CONDA/bin"
    fi
    if [ "$AGENT_OS" == "Windows_NT" ]
      then
        echo "##vso[task.prependpath]$CONDA/Scripts"
    fi
  displayName: Add conda to PATH

- bash: |
    if [ "$AGENT_OS" == "Darwin" ]
      then
        sudo chown -R $USER $CONDA
      fi
  displayName: Take ownership of conda installation

  # Caching post-task takes quite a bit of time.  Disabling it.
  # See: https://github.com/inaos/iron-array/issues/311
  #- task: CacheBeta@0
  #  inputs:
  #  key: v1 | conda | $(Agent.OS)
  #  path: $(CONDA_CACHE_FOLDER)
  #  cacheHitVar: CACHE_RESTORED
  #displayName: 'Cache CONDA'

- bash: |
    conda update --yes -n base -c defaults conda
    conda install -y -c intel mkl-include
    conda install -y -c intel mkl-static
    conda install -y -c intel icc_rt
    conda install -y -c numba 'llvmdev>=11'
    # conda install -y -c numba llvmlite
    conda install -y numpy
    conda install -y pytest
  displayName: Download dependencies
  condition: ne(variables.CACHE_RESTORED, 'true')

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- bash: |
      python -m pip install --retries 3 -U -r requirements.txt
  displayName: 'Install dependencies'

- bash: |
      echo $CONDA
      echo $CONDA_PREFIX
      echo $MKLROOT
      echo $SVMLROOT
      python setup.py build_ext -j 4 --build-type=RelWithDebInfo -- -DDISABLE_LLVM_CONFIG=$DISABLE_LLVM_CONFIG -DLLVM_DIR=$CONDA/lib/cmake/llvm
  displayName: 'Compile package'
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  env:
    MKLROOT: $(CONDA)
    SVMLROOT: $(CONDA)/lib

- script: |
      call "C:\Program Files\%VSINSTALL%\vcvarsall.bat" %MSVC_PLATFORM%
      python setup.py build_ext -i --build-type RelWithDebInfo --generator "NMake Makefiles" -- -DINAC_TARGET_ARCH=x86_64 -DLLVM_DIR=%CONDA%/Library/lib/cmake/llvm -DWINGEN="NMake Makefiles"
      rem copy the necesssary DLLs into iarray package
      copy iarray\iarray-c-develop\build\iarray.dll iarray
      copy iarray\iarray-c-develop\build\svml_dispmd.dll iarray
  displayName: 'Compile package'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  env:
    MKLROOT: $(CONDA)
    SVMLROOT: $(CONDA)/Library/lib

- bash: |
      python -m pip install pytest pytest-azurepipelines pytest-cov msgpack
      LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA/lib pytest -vv -s --test-run-title="Linux test suite" --cov-config=.coveragerc --cov=iarray --cov-report=xml --cov-report=html
  displayName: 'Run Tests'
  condition:
    eq( variables['Agent.OS'], 'Linux' )

- bash: |
      python -m pip install pytest pytest-azurepipelines pytest-cov msgpack
      LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/miniconda/lib pytest -vv -s --test-run-title="Mac test suite" --cov-config=.coveragerc --cov=iarray --cov-report=xml --cov-report=html
  displayName: 'Run Tests'
  condition:
    eq( variables['Agent.OS'], 'Darwin' )

- script: |
      pip install pytest pytest-azurepipelines pytest-cov pytest-cov msgpack
      PATH=%PATH%;C:\Miniconda/Library/bin
      pytest -vv -s --test-run-title="Windows test suite" --cov-config=.coveragerc --cov=iarray --cov-report=xml --cov-report=html iarray/tests/
  displayName: 'Run Tests'
  condition:
    eq( variables['Agent.OS'], 'Windows_NT' )

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  displayName: "Upload Coverage results"
