trigger:
- ci-wheels

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
      python.version: '3.7'
    mac:
      imageName: 'macos-10.14'
      python.version: '3.7'
    windows:
      imageName: 'vs2017-win2016'
      VSINSTALL: "Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build"
      MSVC_PLATFORM: amd64
      python.version: '3.7'

pool:
  vmImage: $(imageName)


steps:
- powershell: gci env:* | sort-object name

- bash: |
    mkdir -p $HOME/.inaos/cmake
    mkdir -p $HOME/INAOS
    echo "INAC_REPOSITORY_LOCAL=$HOME/INAOS" > $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_REMOTE=https://inaos.jfrog.io/inaos/libs-release-local/inaos" >> $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_USRPWD=licensed:AKCp5bBraH7CasbsYCURsjzkbjXwVwdYcT7u39EiuL6GjnK1VKfKQWCd1E2E64mHokU5YUHku" >> $HOME/.inaos/cmake/repository.txt
    git submodule update --init --recursive
  displayName: Clone repos

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
      python -m pip install --retries 3 -U pip setuptools setuptools-scm scikit-build numpy
      python -m pip install -Iv Cython==0.25.2
  displayName: 'Install dependencies'

- script: |
      python setup.py build_ext -i --build-type RelWithDebInfo
  displayName: 'Compile package'
  condition: ne( variables['Agent.OS'], 'Windows_NT' )

- script: |
      call "C:\Program Files (x86)\%VSINSTALL%\vcvarsall.bat" %MSVC_PLATFORM%
      python setup.py build_ext -i --build-type RelWithDebInfo --generator "Visual Studio 15 2017 Win64"
  displayName: 'Compile package'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- script: |
    ls -l
    cat iarray/iarray_ext.c
  displayName: 'Cat C ext'

- script: |
      pip install pytest
      LD_LIBRARY_PATH=$HOME/.inaos/cmake/iarray-linux-x86_64-relwithdebinfo-0.1.4/lib pytest
  displayName: 'Run Tests'
  condition:
    ne( variables['Agent.OS'], 'Windows_NT' )

- script: |
      pip install pytest
      set PATH=%PATH%;%USERPROFILE%\.inaos\cmake\iarray-linux-x86_64-relwithdebinfo-0.1.4\lib
      pytest
  displayName: 'Run Tests'
  condition:
    eq( variables['Agent.OS'], 'Windows_NT' )
