trigger:
- develop

variables:
  CONDA_CACHE_FOLDER: $(CONDA)

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python.version: '3.8'
      DISABLE_LLVM_CONFIG: True
    mac:
      imageName: 'macos-10.15'
      python.version: '3.7'
      DISABLE_LLVM_CONFIG: True
    windows:
      imageName: 'windows-2022'
      VSINSTALL: "Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build"
      MSVC_PLATFORM: amd64
      python.version: '3.9'

pool:
  vmImage: $(imageName)


steps:
- checkout: self
  submodules: recursive
  persistCredentials: true

- powershell: gci env:* | sort-object name

- bash: |
    mkdir -p $HOME/.inaos/cmake
    mkdir -p $HOME/INAOS
    echo "INAC_REPOSITORY_LOCAL=$HOME/INAOS" > $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_REMOTE=https://inaos.jfrog.io/inaos/libs-release-local/inaos" >> $HOME/.inaos/cmake/repository.txt
    echo "INAC_REPOSITORY_USRPWD=licensed:AKCp5bBraH7CasbsYCURsjzkbjXwVwdYcT7u39EiuL6GjnK1VKfKQWCd1E2E64mHokU5YUHku" >> $HOME/.inaos/cmake/repository.txt
    git submodule update --init --recursive
  displayName: Clone repos

- bash: |
    if [ "$AGENT_OS" == "Windows_NT" ]
      then
        echo "##vso[task.prependpath]$CONDA/Scripts"
    else
        echo "##vso[task.prependpath]$CONDA/bin"
    fi
  displayName: Add conda to PATH

- bash: |
    if [ "$AGENT_OS" == "Darwin" ]
      then
        sudo chown -R $USER $CONDA
      fi
  displayName: Take ownership of conda installation

# *** Important note ***
# This activates the 'hosted' version of Python, not the conda one.
# However, as we don't want to use conda environments (I don't have patience enough for handling
# Windows conda environments), we will use this one.  Indeed, all conda packages will still be
# installed (as per the $CONDA/bin path added above), but we will need to use them explicitly
# either via env vars (LD_LIBRARY_PATH) or cmake symbols (LLVM_DIR) or copying DLLs explicitly.
# Yeah, that's a mess, life is hard and all of that, but this WORKS...
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

  # Caching post-task takes quite a bit of time.  Disabling it.
  # See: https://github.com/inaos/iron-array/issues/311
  #- task: CacheBeta@0
  #  inputs:
  #  key: v1 | conda | $(Agent.OS)
  #  path: $(CONDA_CACHE_FOLDER)
  #  cacheHitVar: CACHE_RESTORED
  #displayName: 'Cache CONDA'

- bash: |
    which python
    python -V
    conda update --yes -n base -c defaults conda
    python -m pip install --upgrade pip
    conda install -y -c intel mkl-include
    conda install -y -c intel mkl-static
    conda install -y -c intel icc_rt
    if [ "$AGENT_OS" == "Windows_NT" ]
      then
        # LLVM 13 from conda-forge is not working for windows yet
        conda install -y -c numba 'llvmdev'
        conda install -y cython  # apparently cython from PyPI is not good for win
    else
        # LLVM 13 is necessary for calling int intrinsics
        conda install -y -c conda-forge 'llvmdev>=13'
        # python -m pip install cython  # for unix cython can be installed from either PyPI or conda
        conda install -y cython  # for unix cython can be installed from either PyPI or conda
    fi
  displayName: Download dependencies
  condition: ne(variables.CACHE_RESTORED, 'true')

- bash: |
    python -m pip install --retries 3 -U -r requirements-build.txt
  displayName: 'Install build dependencies'

- bash: |
    python setup.py build_ext -j 4 --build-type=RelWithDebInfo -- -DDISABLE_LLVM_CONFIG=$DISABLE_LLVM_CONFIG -DLLVM_DIR=$CONDA/lib/cmake/llvm
  displayName: 'Compile package'
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  env:
    # The $(CONDA_PREFIX) does not exist on Azure pipelines.  $(CONDA) is fine.
    MKLROOT: $(CONDA)
    SVMLROOT: $(CONDA)/lib

- script: |
    call "C:\Program Files\%VSINSTALL%\vcvarsall.bat" %MSVC_PLATFORM%
    python setup.py build_ext -i --build-type RelWithDebInfo --generator "NMake Makefiles" -- -DINAC_TARGET_ARCH=x86_64 -DLLVM_DIR=%CONDA%/Library/lib/cmake/llvm -DWINGEN="NMake Makefiles"
    rem copy the necesssary DLLs into iarray package
    copy iarray\iarray-c-develop\build\iarray.dll iarray
    copy iarray\iarray-c-develop\build\svml_dispmd.dll iarray
  displayName: 'Compile package'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  env:
    MKLROOT: $(CONDA)/Library
    SVMLROOT: $(CONDA)/Library/lib

- bash: |
    python -m pip install pytest-azurepipelines pytest-cov
    python -m pip install --retries 3 -U -r requirements-test.txt
    python -m pip install --retries 3 -U -r requirements-runtime.txt
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA/lib pytest -vv -s --test-run-title="Linux test suite" --cov-config=.coveragerc --cov=iarray --cov-report=xml --cov-report=html
  displayName: 'Run Tests'
  condition:
    ne( variables['Agent.OS'], 'Windows_NT' )

- script: |
    pip install pytest pytest-azurepipelines pytest-cov
    python -m pip install --retries 3 -U -r requirements-test.txt
    python -m pip install --retries 3 -U -r requirements-runtime.txt
    PATH=%PATH%;C:\Miniconda/Library/bin
    pytest -vv -s --test-run-title="Windows test suite" --cov-config=.coveragerc --cov=iarray --cov-report=xml --cov-report=html iarray/tests/
  displayName: 'Run Tests'
  condition:
    eq( variables['Agent.OS'], 'Windows_NT' )

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  displayName: "Upload Coverage results"
